# Generated by Django 4.1 on 2022-09-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Document', models.IntegerField(primary_key=True, serialize=False)),
                ('nameuser', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('rol', models.CharField(max_length=30)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcooperativa.cliente')),
            ],
        ),
    ]
